# file: logic/constants.py
CARD_FOLDER = "assets/cards"
CARD_BACK_IMAGE = "assets/cards/back.png"
ELIMINATED_IMAGE = "assets/cards/back.png"

CARDS_DATA_RAW = {
    'Guard': {'value': 1, 'vietnamese_name': 'canve',
              'description': "Đoán lá bài của người chơi khác (không phải Cận vệ). Nếu đúng, người đó bị loại.",
              'count_classic': 5, 'count_large': 8},
    'Priest': {'value': 2, 'vietnamese_name': 'mucsu',
               'description': "Nhìn bài trên tay một người chơi khác.",
               'count_classic': 2, 'count_large': 0},
    'Baron': {'value': 3, 'vietnamese_name': 'namtuoc',
              'description': "So bài; người có bài giá trị thấp hơn sẽ bị loại.",
              'count_classic': 2, 'count_large': 0},
    'Handmaid': {'value': 4, 'vietnamese_name': 'cohau',
                 'description': "Miễn nhiễm với hiệu ứng của các lá bài khác cho đến lượt tiếp theo của bạn.",
                 'count_classic': 2, 'count_large': 0},
    'Prince': {'value': 5, 'vietnamese_name': 'hoangtu',
               'description': "Chọn một người chơi (có thể là bạn) để bỏ bài trên tay và rút một lá mới.",
               'count_classic': 2, 'count_large': 0},
    'King': {'value': 6, 'vietnamese_name': 'nhavua',
             'description': "Tráo đổi bài trên tay với một người chơi khác.",
             'count_classic': 1, 'count_large': 0},
    'Countess': {'value': 7, 'vietnamese_name': 'nubatuoc',
                 'description': "Phải bỏ lá này nếu trên tay bạn có Vua hoặc Hoàng tử.",
                 'count_classic': 1, 'count_large': 0},
    'Princess': {'value': 8, 'vietnamese_name': 'congchua',
                 'description': "Bạn sẽ bị loại nếu bỏ lá bài này.",
                 'count_classic': 1, 'count_large': 0},
    'Assassin': {'value': 0, 'vietnamese_name': 'satthu',
                 'description': "Nếu bị Cận vệ nhắm đến, người chơi Cận vệ sẽ bị loại. Bỏ lá này và rút lá mới.",
                 'count_classic': 0, 'count_large': 1},
    'Jester': {'value': 0, 'vietnamese_name': 'tenhe',
               'description': "Chọn một người chơi. Nếu họ thắng vòng này, bạn cũng nhận được một tín vật.",
               'count_classic': 0, 'count_large': 1},
    'Cardinal': {'value': 2, 'vietnamese_name': 'hongy',
                 'description': "Hai người chơi đổi bài cho nhau. Bạn được nhìn một trong hai lá bài đó.",
                 'count_classic': 0, 'count_large': 2},
    'Baroness': {'value': 3, 'vietnamese_name': 'nunamtuoc',
                 'description': "Nhìn bài trên tay của 1 hoặc 2 người chơi khác.",
                 'count_classic': 0, 'count_large': 2},
    'Sycophant': {'value': 4, 'vietnamese_name': 'keninhbo',
                  'description': "Người bị chọn phải tự chọn mình làm mục tiêu cho lá bài hiệu ứng tiếp theo.",
                  'count_classic': 0, 'count_large': 2},
    'Count': {'value': 5, 'vietnamese_name': 'batuoc',
              'description': "+1 vào giá trị bài trên tay nếu lá này nằm trong chồng bài bỏ của bạn.",
              'count_classic': 0, 'count_large': 2},
    'Sheriff': {'value': 6, 'vietnamese_name': 'nguyensoai',
                'description': "Nếu bạn bị loại khi có lá này trong chồng bài bỏ, bạn nhận được một tín vật.",
                'count_classic': 0, 'count_large': 1},
    'Queen Mother': {'value': 7, 'vietnamese_name': 'nuhoang',
                     'description': "So bài; người có bài giá trị cao hơn sẽ bị loại.",
                     'count_classic': 0, 'count_large': 1},
    'Bishop': {'value': 9, 'vietnamese_name': 'giammuc',
               'description': "Đoán giá trị lá bài (không phải Cận vệ). Nhận một tín vật nếu đúng. Người bị đoán có thể rút lại bài.",
               'count_classic': 0, 'count_large': 1},
}

CARD_PROTOTYPES = {}  # Will be populated by Card objects from the UI side

